from chord import *
""" C Chords"""
#C basic
CM = Major_Triad(do)
Cm = Minor_Triad(do)
Caug = Aug_Triad(do)
Cdim = Dim_Triad(do)
Cmb5 = Dim_Triad(do)
#C Major
CM7 = CM.major_seventh()
CM6 = CM.sixth()
Cdom7 = CM.dominant_seventh()
Cdom9 = CM.dominant_ninth()
Cdom11 = CM.dominant_eleventh()
Cdom13 = CM.dominant_thirteenth()
Cadd9 = CM.add(['M9'])
C7add9 = Cdom7.add(['M9'])
CM7add9 = CM7.add(['M9'])
Cadd11 = CM.add(['P11'])
C69 = CM.add(['M6','M9'])
Csus2 = CM.sus2()
Csus4 = CM.sus4()
C7sus4 = CM7.sus4()
#C minor
Cm7 = Cm.seventh()
CmM7 = Cm.major_seventh()
Cm6 = Cm.sixth()
#C augmented
Caug7 = Caug.seventh()
CaugM7 = Caug.major_seventh()
#C diminished
Cdim7 = Cdim.seventh()
Cm7b5 = Cdim.half_seventh()

""" D Chords"""
DM = Major_Triad(re)
Dm = Minor_Triad(re)
Daug = Aug_Triad(re)
Ddim = Dim_Triad(re)
Dmb5 = Dim_Triad(re)

DM7 = DM.major_seventh()
DM6 = DM.sixth()
Ddom7 = DM.dominant_seventh()
Ddom9 = DM.dominant_ninth()
Ddom11 = DM.dominant_eleventh()
Ddom13 = DM.dominant_thirteenth()
Dadd9 = DM.add(['M9'])
D7add9 = Ddom7.add(['M9'])
DM7add9 = DM7.add(['M9'])
Dadd11 = DM.add(['P11'])
D69 = DM.add(['M6','M9'])
Dsus2 = DM.sus2()
Dsus4 = DM.sus4()
D7sus4 = DM7.sus4()

Dm7 = Dm.seventh()
DmM7 = Dm.major_seventh()
Dm6 = Dm.sixth()

Daug7 = Daug.seventh()
DaugM7 = Daug.major_seventh()

Ddim7 = Ddim.seventh()
Dm7b5 = Ddim.half_seventh()

""" E Chords"""
EM = Major_Triad(mi)
Em = Minor_Triad(mi)
Eaug = Aug_Triad(mi)
Edim = Dim_Triad(mi)
Emb5 = Dim_Triad(mi)

EM7 = EM.major_seventh()
EM6 = EM.sixth()
Edom7 = EM.dominant_seventh()
Edom9 = EM.dominant_ninth()
Edom11 = EM.dominant_eleventh()
Edom13 = EM.dominant_thirteenth()
Eadd9 = EM.add(['M9'])
E7add9 = Edom7.add(['M9'])
EM7add9 = EM7.add(['M9'])
Eadd11 = EM.add(['P11'])
E69 = EM.add(['M6','M9'])
Esus2 = EM.sus2()
Esus4 = EM.sus4()
E7sus4 = EM7.sus4()

Em7 = Em.seventh()
EmM7 = Em.major_seventh()
Em6 = Em.sixth()

Eaug7 = Eaug.seventh()
EaugM7 = Eaug.major_seventh()

Edim7 = Edim.seventh()
Em7b5 = Edim.half_seventh()

""" F Chords"""
FM = Major_Triad(fa)
Fm = Minor_Triad(fa)
Faug = Aug_Triad(fa)
Fdim = Dim_Triad(fa)
Fmb5 = Dim_Triad(fa)

FM7 = FM.major_seventh()
FM6 = FM.sixth()
Fdom7 = FM.dominant_seventh()
Fdom9 = FM.dominant_ninth()
Fdom11 = FM.dominant_eleventh()
Fdom13 = FM.dominant_thirteenth()
Fadd9 = FM.add(['M9'])
F7add9 = Fdom7.add(['M9'])
FM7add9 = FM7.add(['M9'])
Fadd11 = FM.add(['P11'])
F69 = FM.add(['M6','M9'])
Fsus2 = FM.sus2()
Fsus4 = FM.sus4()
F7sus4 = FM7.sus4()

Fm7 = Fm.seventh()
FmM7 = Fm.major_seventh()
Fm6 = Fm.sixth()

Faug7 = Faug.seventh()
FaugM7 = Faug.major_seventh()

Fdim7 = Fdim.seventh()
Fm7b5 = Fdim.half_seventh()

""" G Chords"""
GM = Major_Triad(so)
Gm = Minor_Triad(so)
Gaug = Aug_Triad(so)
Gdim = Dim_Triad(so)
Gmb5 = Dim_Triad(so)

GM7 = GM.major_seventh()
GM6 = GM.sixth()
Gdom7 = GM.dominant_seventh()
Gdom9 = GM.dominant_ninth()
Adom11 = GM.dominant_eleventh()
Adom13 = GM.dominant_thirteenth()
Gadd9 = GM.add(['M9'])
G7add9 = Gdom7.add(['M9'])
GM7add9 = GM7.add(['M9'])
Gadd11 = GM.add(['P11'])
G69 = GM.add(['M6','M9'])
Gsus2 = GM.sus2()
Gsus4 = GM.sus4()
G7sus4 = GM7.sus4()

Gm7 = Gm.seventh()
GmM7 = Gm.major_seventh()
Gm6 = Gm.sixth()

Gaug7 = Gaug.seventh()
GaugM7 = Gaug.major_seventh()

Gdim7 = Gdim.seventh()
Gm7b5 = Gdim.half_seventh()

""" A Chords"""
AM = Major_Triad(la)
Am = Minor_Triad(la)
Aaug = Aug_Triad(la)
Adim = Dim_Triad(la)
Amb5 = Dim_Triad(la)

AM7 = AM.major_seventh()
AM6 = AM.sixth()
Adom7 = AM.dominant_seventh()
Adom9 = AM.dominant_ninth()
Gdom11 = AM.dominant_eleventh()
Gdom13 = AM.dominant_thirteenth()
Aadd9 = AM.add(['M9'])
A7add9 = Adom7.add(['M9'])
AM7add9 = AM7.add(['M9'])
Aadd11 = AM.add(['P11'])
A69 = AM.add(['M6','M9'])
Asus2 = AM.sus2()
Asus4 = AM.sus4()
A7sus4 = AM7.sus4()

Am7 = Am.seventh()
AmM7 = Am.major_seventh()
Am6 = Am.sixth()

Aaug7 = Aaug.seventh()
AaugM7 = Aaug.major_seventh()

Adim7 = Adim.seventh()
Am7b5 = Adim.half_seventh()

""" B Chords"""
BM = Major_Triad(si)
Bm = Minor_Triad(si)
Baug = Aug_Triad(si)
Bdim = Dim_Triad(si)
Bmb5 = Dim_Triad(si)

BM7 = BM.major_seventh()
BM6 = BM.sixth()
Bdom7 = BM.dominant_seventh()
Bdom9 = BM.dominant_ninth()
Bdom11 = BM.dominant_eleventh()
Bdom13 = BM.dominant_thirteenth()
Badd9 = BM.add(['M9'])
B7add9 = Bdom7.add(['M9'])
BM7add9 = BM7.add(['M9'])
Badd11 = BM.add(['P11'])
B69 = BM.add(['M6','M9'])
Bsus2 = BM.sus2()
Bsus4 = BM.sus4()
B7sus4 = BM7.sus4()

Bm7 = Bm.seventh()
BmM7 = Bm.major_seventh()
Bm6 = Bm.sixth()

Baug7 = Baug.seventh()
BaugM7 = Baug.major_seventh()

Bdim7 = Bdim.seventh()
Bm7b5 = Bdim.half_seventh()

""" Cb Chords"""
CbM = Major_Triad(si)
Cbm = Minor_Triad(si)
Cbaug = Aug_Triad(si)
Cbdim = Dim_Triad(si)
Cbmb5 = Dim_Triad(si)

CbM7 = CbM.major_seventh()
CbM6 = CbM.sixth()
Cbdom7 = CbM.dominant_seventh()
Cbdom9 = CbM.dominant_ninth()
Cbdom11 = CbM.dominant_eleventh()
Cbdom13 = CbM.dominant_thirteenth()
Cbadd9 = CbM.add(['M9'])
Cb7add9 = Cbdom7.add(['M9'])
CbM7add9 = CbM7.add(['M9'])
Cbadd11 = CbM.add(['P11'])
Cb69 = CbM.add(['M6','M9'])
Cbsus2 = CbM.sus2()
Cbsus4 = CbM.sus4()
Cb7sus4 = CbM7.sus4()

Cbm7 = Cbm.seventh()
CbmM7 = Cbm.major_seventh()
Cbm6 = Cbm.sixth()

Cbaug7 = Cbaug.seventh()
CbaugM7 = Cbaug.major_seventh()

Cbdim7 = Cbdim.seventh()
Cbm7b5 = Cbdim.half_seventh()

""" Cs Chords"""
CsM = Major_Triad(de)
Csm = Minor_Triad(de)
Csaug = Aug_Triad(de)
Csdim = Dim_Triad(de)
Csmb5 = Dim_Triad(de)

CsM7 = CsM.major_seventh()
CsM6 = CsM.sixth()
Csdom7 = CsM.dominant_seventh()
Csdom9 = CsM.dominant_ninth()
Csdom11 = CsM.dominant_eleventh()
Csdom13 = CsM.dominant_thirteenth()
Csadd9 = CsM.add(['M9'])
Cs7add9 = Csdom7.add(['M9'])
CsM7add9 = CsM7.add(['M9'])
Csadd11 = CsM.add(['P11'])
Cs69 = CsM.add(['M6','M9'])
Cssus2 = CsM.sus2()
Cssus4 = CsM.sus4()
Cs7sus4 = CsM7.sus4()

Csm7 = Csm.seventh()
CsmM7 = Csm.major_seventh()
Csm6 = Csm.sixth()

Csaug7 = Csaug.seventh()
CsaugM7 = Csaug.major_seventh()

Csdim7 = Csdim.seventh()
Csm7b5 = Csdim.half_seventh()

""" Db Chords"""
DbM = Major_Triad(de)
Dbm = Minor_Triad(de)
Dbaug = Aug_Triad(de)
Dbdim = Dim_Triad(de)
Dbmb5 = Dim_Triad(de)

DbM7 = DbM.major_seventh()
DbM6 = DbM.sixth()
Dbdom7 = DbM.dominant_seventh()
Dbdom9 = DbM.dominant_ninth()
Dbdom11 = DbM.dominant_eleventh()
Dbdom13 = DbM.dominant_thirteenth()
Dbadd9 = DbM.add(['M9'])
Db7add9 = Dbdom7.add(['M9'])
DbM7add9 = DbM7.add(['M9'])
Dbadd11 = DbM.add(['P11'])
Db69 = DbM.add(['M6','M9'])
Dbsus2 = DbM.sus2()
Dbsus4 = DbM.sus4()
Db7sus4 = DbM7.sus4()

Dbm7 = Dbm.seventh()
DbmM7 = Dbm.major_seventh()
Dbm6 = Dbm.sixth()

Dbaug7 = Dbaug.seventh()
DbaugM7 = Dbaug.major_seventh()

Dbdim7 = Dbdim.seventh()
Dbm7b5 = Dbdim.half_seventh()

""" Ds Chords"""
DsM = Major_Triad(ri)
Dsm = Minor_Triad(ri)
Dsaug = Aug_Triad(ri)
Dsdim = Dim_Triad(ri)
Dsmb5 = Dim_Triad(ri)

DsM7 = DsM.major_seventh()
DsM6 = DsM.sixth()
Dsdom7 = DsM.dominant_seventh()
Dsdom9 = DsM.dominant_ninth()
Dsdom11 = DsM.dominant_eleventh()
Dsdom13 = DsM.dominant_thirteenth()
Dsadd9 = DsM.add(['M9'])
Ds7add9 = Dsdom7.add(['M9'])
DsM7add9 = DsM7.add(['M9'])
Dsadd11 = DsM.add(['P11'])
Ds69 = DsM.add(['M6','M9'])
Dssus2 = DsM.sus2()
Dssus4 = DsM.sus4()
Ds7sus4 = DsM7.sus4()

Dsm7 = Dsm.seventh()
DsmM7 = Dsm.major_seventh()
Dsm6 = Dsm.sixth()

Dsaug7 = Dsaug.seventh()
DsaugM7 = Dsaug.major_seventh()

Dsdim7 = Dsdim.seventh()
Dsm7b5 = Dsdim.half_seventh()

""" Eb Chords"""
EbM = Major_Triad(ri)
Ebm = Minor_Triad(ri)
Ebaug = Aug_Triad(ri)
Ebdim = Dim_Triad(ri)
Ebmb5 = Dim_Triad(ri)

EbM7 = EbM.major_seventh()
EbM6 = EbM.sixth()
Ebdom7 = EbM.dominant_seventh()
Ebdom9 = EbM.dominant_ninth()
Ebdom11 = EbM.dominant_eleventh()
Ebdom13 = EbM.dominant_thirteenth()
Ebadd9 = EbM.add(['M9'])
Eb7add9 = Ebdom7.add(['M9'])
EbM7add9 = EbM7.add(['M9'])
Ebadd11 = EbM.add(['P11'])
Eb69 = EbM.add(['M6','M9'])
Ebsus2 = EbM.sus2()
Ebsus4 = EbM.sus4()
Eb7sus4 = EbM7.sus4()

Ebm7 = Ebm.seventh()
EbmM7 = Ebm.major_seventh()
Ebm6 = Ebm.sixth()

Ebaug7 = Ebaug.seventh()
EbaugM7 = Ebaug.major_seventh()

Ebdim7 = Ebdim.seventh()
Ebm7b5 = Ebdim.half_seventh()

""" Es Chords"""
EsM = Major_Triad(fa)
Esm = Minor_Triad(fa)
Esaug = Aug_Triad(fa)
Esdim = Dim_Triad(fa)
Esmb5 = Dim_Triad(fa)

EsM7 = EsM.major_seventh()
EsM6 = EsM.sixth()
Esdom7 = EsM.dominant_seventh()
Esdom9 = EsM.dominant_ninth()
Esdom11 = EsM.dominant_eleventh()
Esdom13 = EsM.dominant_thirteenth()
Esadd9 = EsM.add(['M9'])
Es7add9 = Esdom7.add(['M9'])
EsM7add9 = EsM7.add(['M9'])
Esadd11 = EsM.add(['P11'])
Es69 = EsM.add(['M6','M9'])
Essus2 = EsM.sus2()
Essus4 = EsM.sus4()
Es7sus4 = EsM7.sus4()

Esm7 = Esm.seventh()
EsmM7 = Esm.major_seventh()
Esm6 = Esm.sixth()

Esaug7 = Esaug.seventh()
EsaugM7 = Esaug.major_seventh()

Esdim7 = Esdim.seventh()
Esm7b5 = Esdim.half_seventh()

""" Fs Chords"""
FsM = Major_Triad(fi)
Fsm = Minor_Triad(fi)
Fsaug = Aug_Triad(fi)
Fsdim = Dim_Triad(fi)
Fsmb5 = Dim_Triad(fi)

FsM7 = FsM.major_seventh()
FsM6 = FsM.sixth()
Fsdom7 = FsM.dominant_seventh()
Fsdom9 = FsM.dominant_ninth()
Fsdom11 = FsM.dominant_eleventh()
Fsdom13 = FsM.dominant_thirteenth()
Fsadd9 = FsM.add(['M9'])
Fs7add9 = Fsdom7.add(['M9'])
FsM7add9 = FsM7.add(['M9'])
Fsadd11 = FsM.add(['P11'])
Fs69 = FsM.add(['M6','M9'])
Fssus2 = FsM.sus2()
Fssus4 = FsM.sus4()
Fs7sus4 = FsM7.sus4()

Fsm7 = Fsm.seventh()
FsmM7 = Fsm.major_seventh()
Fsm6 = Fsm.sixth()

Fsaug7 = Fsaug.seventh()
FsaugM7 = Fsaug.major_seventh()

Fsdim7 = Fsdim.seventh()
Fsm7b5 = Fsdim.half_seventh()

""" Gb Chords"""
GbM = Major_Triad(fi)
Gbm = Minor_Triad(fi)
Gbaug = Aug_Triad(fi)
Gbdim = Dim_Triad(fi)
Gbmb5 = Dim_Triad(fi)

GbM7 = GbM.major_seventh()
GbM6 = GbM.sixth()
Gbdom7 = GbM.dominant_seventh()
Gbdom9 = GbM.dominant_ninth()
Gbdom11 = GbM.dominant_eleventh()
Gbdom13 = GbM.dominant_thirteenth()
Gbadd9 = GbM.add(['M9'])
Gb7add9 = Gbdom7.add(['M9'])
GbM7add9 = GbM7.add(['M9'])
Gbadd11 = GbM.add(['P11'])
Gb69 = GbM.add(['M6','M9'])
Gbsus2 = GbM.sus2()
Gbsus4 = GbM.sus4()
Gb7sus4 = GbM7.sus4()

Gbm7 = Gbm.seventh()
GbmM7 = Gbm.major_seventh()
Gbm6 = Gbm.sixth()

Gbaug7 = Gbaug.seventh()
GbaugM7 = Gbaug.major_seventh()

Gbdim7 = Gbdim.seventh()
Gbm7b5 = Gbdim.half_seventh()

""" Gs Chords"""
GsM = Major_Triad(sa)
Gsm = Minor_Triad(sa)
Gsaug = Aug_Triad(sa)
Gsdim = Dim_Triad(sa)
Gsmb5 = Dim_Triad(sa)

GsM7 = GsM.major_seventh()
GsM6 = GsM.sixth()
Gsdom7 = GsM.dominant_seventh()
Gsdom9 = GsM.dominant_ninth()
Gsdom11 = GsM.dominant_eleventh()
Gsdom13 = GsM.dominant_thirteenth()
Gsadd9 = GsM.add(['M9'])
Gs7add9 = Gsdom7.add(['M9'])
GsM7add9 = GsM7.add(['M9'])
Gsadd11 = GsM.add(['P11'])
Gs69 = GsM.add(['M6','M9'])
Gssus2 = GsM.sus2()
Gssus4 = GsM.sus4()
Gs7sus4 = GsM7.sus4()

Gsm7 = Gsm.seventh()
GsmM7 = Gsm.major_seventh()
Gsm6 = Gsm.sixth()

Gsaug7 = Gsaug.seventh()
GsaugM7 = Gsaug.major_seventh()

Gsdim7 = Gsdim.seventh()
Gsm7b5 = Gsdim.half_seventh()

""" Ab Chords"""
AbM = Major_Triad(sa)
Abm = Minor_Triad(sa)
Abaug = Aug_Triad(sa)
Abdim = Dim_Triad(sa)
Abmb5 = Dim_Triad(sa)

AbM7 = AbM.major_seventh()
AbM6 = AbM.sixth()
Abdom7 = AbM.dominant_seventh()
Abdom9 = AbM.dominant_ninth()
Abdom11 = AbM.dominant_eleventh()
Abdom13 = AbM.dominant_thirteenth()
Abadd9 = AbM.add(['M9'])
Ab7add9 = Abdom7.add(['M9'])
AbM7add9 = AbM7.add(['M9'])
Abadd11 = AbM.add(['P11'])
Ab69 = AbM.add(['M6','M9'])
Absus2 = AbM.sus2()
Absus4 = AbM.sus4()
Ab7sus4 = AbM7.sus4()

Abm7 = Abm.seventh()
AbmM7 = Abm.major_seventh()
Abm6 = Abm.sixth()

Abaug7 = Abaug.seventh()
AbaugM7 = Abaug.major_seventh()

Abdim7 = Abdim.seventh()
Abm7b5 = Abdim.half_seventh()

""" As Chords"""
AsM = Major_Triad(chi)
Asm = Minor_Triad(chi)
Asaug = Aug_Triad(chi)
Asdim = Dim_Triad(chi)
Asmb5 = Dim_Triad(chi)

AsM7 = AsM.major_seventh()
AsM6 = AsM.sixth()
Asdom7 = AsM.dominant_seventh()
Asdom9 = AsM.dominant_ninth()
Asdom11 = AsM.dominant_eleventh()
Asdom13 = AsM.dominant_thirteenth()
Asadd9 = AsM.add(['M9'])
As7add9 = Asdom7.add(['M9'])
AsM7add9 = AsM7.add(['M9'])
Asadd11 = AsM.add(['P11'])
As69 = AsM.add(['M6','M9'])
Assus2 = AsM.sus2()
Assus4 = AsM.sus4()
As7sus4 = AsM7.sus4()

Asm7 = Asm.seventh()
AsmM7 = Asm.major_seventh()
Asm6 = Asm.sixth()

Asaug7 = Asaug.seventh()
AsaugM7 = Asaug.major_seventh()

Asdim7 = Asdim.seventh()
Asm7b5 = Asdim.half_seventh()

""" Bb Chords"""
BbM = Major_Triad(chi)
Bbm = Minor_Triad(chi)
Bbaug = Aug_Triad(chi)
Bbdim = Dim_Triad(chi)
Bbmb5 = Dim_Triad(chi)

BbM7 = BbM.major_seventh()
BbM6 = BbM.sixth()
Bbdom7 = BbM.dominant_seventh()
Bbdom9 = BbM.dominant_ninth()
Bbdom11 = BbM.dominant_eleventh()
Bbdom13 = BbM.dominant_thirteenth()
Bbadd9 = BbM.add(['M9'])
Bb7add9 = Bbdom7.add(['M9'])
BbM7add9 = BbM7.add(['M9'])
Bbadd11 = BbM.add(['P11'])
Bb69 = BbM.add(['M6','M9'])
Bbsus2 = BbM.sus2()
Bbsus4 = BbM.sus4()
Bb7sus4 = BbM7.sus4()

Bbm7 = Bbm.seventh()
BbmM7 = Bbm.major_seventh()
Bbm6 = Bbm.sixth()

Bbaug7 = Bbaug.seventh()
BbaugM7 = Bbaug.major_seventh()

Bbdim7 = Bbdim.seventh()
Bbm7b5 = Bbdim.half_seventh()

""" Bs Chords"""
BsM = Major_Triad(do)
Bsm = Minor_Triad(do)
Bsaug = Aug_Triad(do)
Bsdim = Dim_Triad(do)
Bsmb5 = Dim_Triad(do)

BsM7 = BsM.major_seventh()
BsM6 = BsM.sixth()
Bsdom7 = BsM.dominant_seventh()
Bsdom9 = BsM.dominant_ninth()
Bsdom11 = BsM.dominant_eleventh()
Bsdom13 = BsM.dominant_thirteenth()
Bsadd9 = BsM.add(['M9'])
Bs7add9 = Bsdom7.add(['M9'])
BsM7add9 = BsM7.add(['M9'])
Bsadd11 = BsM.add(['P11'])
Bs69 = BsM.add(['M6','M9'])
Bssus2 = BsM.sus2()
Bssus4 = BsM.sus4()
Bs7sus4 = BsM7.sus4()

Bsm7 = Bsm.seventh()
BsmM7 = Bsm.major_seventh()
Bsm6 = Bsm.sixth()

Bsaug7 = Bsaug.seventh()
BsaugM7 = Bsaug.major_seventh()

Bsdim7 = Bsdim.seventh()
Bsm7b5 = Bsdim.half_seventh()
